name = "dac-bot-integrated"
compatibility_date = "2024-04-01"
main = "src/index.ts"

[[ d1_databases ]]
binding = 'DB'
database_name = 'mesugaki-db'
database_id = '96ac9927-7680-4dc8-a049-d948ca5c5947'

[vars]
DISCORD_PUBLIC_KEY = "517ef0d340e531768604c0a1cf97d85c32b66a3204da70ba8fa91e2ec2fbf34f"
API_BASE_URL = "https://dac-bot-integrated.kurosiko.workers.dev"

# [assets]
# directory = "./public"