name = "dac-bot-integrated"
compatibility_date = "2024-04-01"
main = "src/index.ts"

[[ d1_databases ]]
binding = 'DB'
database_name = 'db eg'
database_id = 'id'

[vars]
DISCORD_PUBLIC_KEY = "key"
API_BASE_URL = "self"

# [assets]
# directory = "./public"